export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_START = 'AUTH_START'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const SEARCH_START = 'SEARCH_START'
export const SEARCH_FAIL = 'SEARCH_FAIL'
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT = 'LOGOUT'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const GET_PHOTOS_REQUEST = 'GET_PHOTOS_REQUEST'
export const GET_PHOTOS_SUCCESS = 'GET_PHOTOS_SUCCESS'
export const GET_PHOTOS_FAIL = 'GET_PHOTOS_FAIL'
